# Generated by Django 2.2.3 on 2019-07-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190717_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grunddaten',
            old_name='sapkonto',
            new_name='sapname',
        ),
    ]
